import SmoothScroll from "@/components/smooth-scroll";
import type { Metadata } from "next";
import { Pacifico, Bebas_Neue, Inter, Rubik } from "next/font/google";
import "./globals.css";

// removed Poppins and Boldonse per request

const pacifico = Pacifico({
    variable: "--font-pacifico",
    subsets: ["latin"],
    weight: "400",
    display: "swap",
});

const bebas = Bebas_Neue({
    variable: "--font-bebas",
    subsets: ["latin"],
    weight: "400",
    display: "swap",
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    display: "swap",
});

const rubik = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
    weight: ["300", "400", "500", "700"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${pacifico.variable} ${bebas.variable} ${inter.variable} ${rubik.variable}`}
            >
                <SmoothScroll>{children}</SmoothScroll>
            </body>
        </html>
    );
}
