import type { Metadata } from "next";
import { Poppins, Boldonse } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "700"],
    display: "swap",
});

const boldonse = Boldonse({
    variable: "--font-boldonse",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} ${boldonse.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
